apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back_service.name }}
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.back_service.selector }}
  ports:
    - port: {{ .Values.back_service.port }}
      targetPort: {{ .Values.back_service.targetPort }}