kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.mysql_configMap.name }} 
data:
  database: {{ .Values.mysql_configMap.database }}
  database_host: {{ .Values.mysql_configMap.database_host }}
  database_username: {{ .Values.mysql_configMap.database_username }}