apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  selector:
    matchLabels:
      app: indexer
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: ibarreche/cloud-indexer-ci
          ports:
            - containerPort: 3000
              name: indexer
          env:
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  name: indexer-configmap
                  key: rabbitmq_url
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: indexer-configmap
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer-secret
                  key: rabbitmq_password
            - name: ELASTICSEARCH_URI
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-configmap
                  key: elasticsearch_url