kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: office
  name: deployment-manager
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicaset", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]