back_deployment:
  image: "ibarreche/cloud-back-ci"
  tag: "latest"
  name: "back"
  replicasNb: 2
  restartPolicy: "Always"
  containerPort: 8000

back_service:
  name: "back-cluster-ip-service"
  selector: "back"
  port: 8000
  targetPort: 8000

rabbitmq_configMap:
  name: "rabbitmq-configmap"
  rabbitmq_url: "amqp://guest:guest@rabbitmq:5672"
  rabbitmq_user: "guest"
  rabbitmq_host: "rabbitmq"
  rabbitmq_vhost: "/"

rabbitmq_secret:
  name: "rabbitmq-secret"

mysql_configMap:
  name: "mysql-configmap"
  database: "laravel"
  database_host: "mysql"
  database_username: "root"
  secret: "mysql-secret"

mysql_secret:
  name: "mysql-secret"

elasticsearch_configMap:
  name: "elasticsearch-configmap"
  elasticsearch_host: "elasticsearch-cluster-ip-service"
  elasticsearch_url: "http://elasticsearch-cluster-ip-service:9200"
  elasticsearch_cluster_name: "elasticsearch"
  elasticsearch_discovery_type: "single-node"
  elasticsearch_es_java_opts: "-Xms512m -Xmx512m"


